<?php


namespace App\Views;


use App\App;
use Core\View;

class Navigation extends View
{
    public function render($template_path = ROOT . '/app/templates/nav.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['Home' => '/index.php'];
        if (App::$session->getUser()) {
            return $nav + [
                    'Add'  => '/admin/add.php',
                    'List'=> '/admin/list.php',
                     'Logout'=> '/logout.php',

                ];
        } else {
            return $nav + [
                    'Register' => '/register.php',
                    'Login' => '/login.php',
                ];
        }
    }

}